CREATE TABLE [EMPLEADO] (
    [ID] int NOT NULL IDENTITY,
    [NOMBRE_COMPLETO] nvarchar(30) NOT NULL,
    [CARGO] nvarchar(30) NOT NULL,
    CONSTRAINT [PK_EMPLEADO] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [SALA] (
    [ID] int NOT NULL IDENTITY,
    [NOMBRE] nvarchar(80) NOT NULL,
    [DESCRIPCION] nvarchar(300) NULL,
    [CAPACIDAD] int NOT NULL,
    [HABILITADA] bit NOT NULL,
    CONSTRAINT [PK_SALA] PRIMARY KEY ([ID])
);
GO


CREATE TABLE [RESERVA] (
    [ID] int NOT NULL IDENTITY,
    [FECHA_HORA] nvarchar(80) NOT NULL,
    [RESERVADO_POR] int NOT NULL,
    [SALA_ID] int NOT NULL,
    CONSTRAINT [PK_RESERVA] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_RESERVA_EMPLEADO_RESERVADO_POR] FOREIGN KEY ([RESERVADO_POR]) REFERENCES [EMPLEADO] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_RESERVA_SALA_SALA_ID] FOREIGN KEY ([SALA_ID]) REFERENCES [SALA] ([ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [ASISTENTES] (
    [ID] int NOT NULL IDENTITY,
    [RESERVA_ID] int NULL,
    [ASISTENTE_ID] int NOT NULL,
    [ASISTIO] bit NOT NULL,
    CONSTRAINT [PK_ASISTENTES] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_ASISTENTES_EMPLEADO_ASISTENTE_ID] FOREIGN KEY ([ASISTENTE_ID]) REFERENCES [EMPLEADO] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_ASISTENTES_RESERVA_RESERVA_ID] FOREIGN KEY ([RESERVA_ID]) REFERENCES [RESERVA] ([ID])
);
GO


CREATE INDEX [IX_ASISTENTES_ASISTENTE_ID] ON [ASISTENTES] ([ASISTENTE_ID]);
GO


CREATE INDEX [IX_ASISTENTES_RESERVA_ID] ON [ASISTENTES] ([RESERVA_ID]);
GO


CREATE INDEX [IX_RESERVA_RESERVADO_POR] ON [RESERVA] ([RESERVADO_POR]);
GO


CREATE INDEX [IX_RESERVA_SALA_ID] ON [RESERVA] ([SALA_ID]);
GO


